circle: # [X_centre,Y_centre,radius]
  [
    [-200, -300, 100],
    [0, 0, 100],
    [200, 300, 100],
    [200, -300, 100],
  ]

boundary: #[x_min,x_max,y_min,y_max]
  [ 
    [-510, -500, -510, 510],
    [500, 510, -510, 510],
    [-510, 510, -510, -500],
    [-510, 510, 500, 510]
  ]

rectangle: #[x_min,x_max,y_min,y_max]
  [
    [-475, -325, -75, 75],
    [325, 475, -75, 75],
    [-375, -225, 225, 375],
  ]